
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND CAR CAR CDR CDR CONS CONS DIV EMPTY EQUAL FALSE GREATER GREATEREQUAL IF LESS LESSEQUAL LPARENT MINUS NOTEQUAL NUMBER OR PLUS RPARENT SEMI TIMES TRUElispStart : lisp SEMIlispStart : bool SEMIlispStart : list SEMIlisp : NUMBERlisp : LPARENT PLUS lisp lisp RPARENTlisp : LPARENT MINUS lisp lisp RPARENTlisp : LPARENT TIMES lisp lisp RPARENTlisp : LPARENT DIV lisp lisp RPARENTlisp : LPARENT IF bool lisp lisp RPARENTlisp : LPARENT CAR list RPARENTbool : TRUEbool : FALSEbool : LPARENT GREATER lisp lisp RPARENTbool : LPARENT GREATEREQUAL lisp lisp RPARENTbool : LPARENT LESS lisp lisp RPARENTbool : LPARENT LESSEQUAL lisp lisp RPARENTbool : LPARENT NOTEQUAL lisp lisp RPARENTbool : LPARENT EQUAL lisp lisp RPARENTbool : LPARENT AND bool bool RPARENTlist : LPARENT list RPARENTlist : lisplist : lisp listlist : LPARENT CONS lisp list RPARENTlist : LPARENT CDR list RPARENTlist : EMPTY'
    
_lr_action_items = {'NUMBER':([0,2,5,6,7,8,10,13,16,17,18,19,21,23,24,25,26,27,28,30,31,33,34,35,36,38,41,42,43,44,45,46,48,54,55,65,66,67,68,70,71,72,73,74,75,76,78,],[5,5,-4,5,-11,-12,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,-10,-5,-6,-7,-8,-13,-14,-15,-16,-17,-18,-19,-9,]),'LPARENT':([0,2,5,6,7,8,10,13,16,17,18,19,20,21,23,24,25,26,27,28,29,30,31,33,34,35,36,38,41,42,43,44,45,46,47,48,54,55,65,66,67,68,70,71,72,73,74,75,76,78,],[6,13,-4,13,-11,-12,13,13,32,32,32,32,37,13,32,32,32,32,32,32,37,32,13,32,32,32,32,32,32,32,32,32,32,32,37,13,32,-10,-5,-6,-7,-8,-13,-14,-15,-16,-17,-18,-19,-9,]),'TRUE':([0,7,8,20,29,47,70,71,72,73,74,75,76,],[7,-11,-12,7,7,7,-13,-14,-15,-16,-17,-18,-19,]),'FALSE':([0,7,8,20,29,47,70,71,72,73,74,75,76,],[8,-11,-12,8,8,8,-13,-14,-15,-16,-17,-18,-19,]),'EMPTY':([0,2,5,6,10,13,21,31,48,55,65,66,67,68,78,],[9,9,-4,9,9,9,9,9,9,-10,-5,-6,-7,-8,-9,]),'$end':([1,11,14,15,],[0,-1,-2,-3,]),'SEMI':([2,3,4,5,7,8,9,10,12,40,55,64,65,66,67,68,70,71,72,73,74,75,76,77,78,],[11,14,15,-4,-11,-12,-25,-21,-22,-20,-10,-24,-5,-6,-7,-8,-13,-14,-15,-16,-17,-18,-19,-23,-9,]),'RPARENT':([5,7,8,9,10,12,22,39,40,49,50,51,52,53,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,],[-4,-11,-12,-25,-21,-22,40,55,-20,64,65,66,67,68,-10,70,71,72,73,74,75,76,77,-24,-5,-6,-7,-8,78,-13,-14,-15,-16,-17,-18,-19,-23,-9,]),'PLUS':([6,13,32,],[16,16,16,]),'MINUS':([6,13,32,],[17,17,17,]),'TIMES':([6,13,32,],[18,18,18,]),'DIV':([6,13,32,],[19,19,19,]),'IF':([6,13,32,],[20,20,20,]),'CAR':([6,13,32,],[21,21,21,]),'GREATER':([6,37,],[23,23,]),'GREATEREQUAL':([6,37,],[24,24,]),'LESS':([6,37,],[25,25,]),'LESSEQUAL':([6,37,],[26,26,]),'NOTEQUAL':([6,37,],[27,27,]),'EQUAL':([6,37,],[28,28,]),'AND':([6,37,],[29,29,]),'CONS':([6,13,],[30,30,]),'CDR':([6,13,],[31,31,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lispStart':([0,],[1,]),'lisp':([0,2,6,10,13,16,17,18,19,21,23,24,25,26,27,28,30,31,33,34,35,36,38,41,42,43,44,45,46,48,54,],[2,10,10,10,10,33,34,35,36,10,41,42,43,44,45,46,48,10,50,51,52,53,54,56,57,58,59,60,61,10,69,]),'bool':([0,20,29,47,],[3,38,47,62,]),'list':([0,2,6,10,13,21,31,48,],[4,12,22,12,22,39,49,63,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lispStart","S'",1,None,None,None),
  ('lispStart -> lisp SEMI','lispStart',2,'p_lispStart_1','LISPParser.py',8),
  ('lispStart -> bool SEMI','lispStart',2,'p_lispStart_2','LISPParser.py',12),
  ('lispStart -> list SEMI','lispStart',2,'p_lispStart_3','LISPParser.py',16),
  ('lisp -> NUMBER','lisp',1,'p_lisp_1','LISPParser.py',27),
  ('lisp -> LPARENT PLUS lisp lisp RPARENT','lisp',5,'p_lisp_2','LISPParser.py',33),
  ('lisp -> LPARENT MINUS lisp lisp RPARENT','lisp',5,'p_lisp_3','LISPParser.py',39),
  ('lisp -> LPARENT TIMES lisp lisp RPARENT','lisp',5,'p_lisp_4','LISPParser.py',45),
  ('lisp -> LPARENT DIV lisp lisp RPARENT','lisp',5,'p_lisp_5','LISPParser.py',51),
  ('lisp -> LPARENT IF bool lisp lisp RPARENT','lisp',6,'p_lisp_6','LISPParser.py',57),
  ('lisp -> LPARENT CAR list RPARENT','lisp',4,'p_lisp_7','LISPParser.py',62),
  ('bool -> TRUE','bool',1,'p_bool_1','LISPParser.py',76),
  ('bool -> FALSE','bool',1,'p_bool_2','LISPParser.py',82),
  ('bool -> LPARENT GREATER lisp lisp RPARENT','bool',5,'p_bool_3','LISPParser.py',88),
  ('bool -> LPARENT GREATEREQUAL lisp lisp RPARENT','bool',5,'p_bool_4','LISPParser.py',94),
  ('bool -> LPARENT LESS lisp lisp RPARENT','bool',5,'p_bool_5','LISPParser.py',100),
  ('bool -> LPARENT LESSEQUAL lisp lisp RPARENT','bool',5,'p_bool_6','LISPParser.py',106),
  ('bool -> LPARENT NOTEQUAL lisp lisp RPARENT','bool',5,'p_bool_7','LISPParser.py',112),
  ('bool -> LPARENT EQUAL lisp lisp RPARENT','bool',5,'p_bool_8','LISPParser.py',118),
  ('bool -> LPARENT AND bool bool RPARENT','bool',5,'p_bool_9','LISPParser.py',124),
  ('list -> LPARENT list RPARENT','list',3,'p_list_1','LISPParser.py',133),
  ('list -> lisp','list',1,'p_list_2','LISPParser.py',137),
  ('list -> lisp list','list',2,'p_list_3','LISPParser.py',141),
  ('list -> LPARENT CONS lisp list RPARENT','list',5,'p_list_5','LISPParser.py',146),
  ('list -> LPARENT CDR list RPARENT','list',4,'p_list_6','LISPParser.py',151),
  ('list -> EMPTY','list',1,'p_list_7','LISPParser.py',155),
]
